### ISSUE TITLE
Delivery form parsing issue in deliver_files.py

### ISSUE THREAD

**Issue by ariley1472** [Vb2341/ReDCaT#23]
When I tried running deliver_files.py, it crashed because it thinks that that entire section ("17. Reason for delivery: blah blah blah") is the reason for delivery, so it crashed because of the colon after "Reason for delivery". I looked to see what the script is doing and it looks like you have already programmed it to take the "17. Reason for delivery:" out but it appears that it's not working.

**Comment by jwhite3** [comment]
I believe that if we get rid of the trailing space here:


1
--
  | description_sans_number= description.split('17. Reason for delivery: ')[-1]

``
it should fix the issue. I think what's happening is that it was failing to actually split the concatenated string, 'description' in some of the delivery forms because there was no space

**Comment by jwhite3** [comment]
This has been fixed hopefully, but I'll hold off on closing for now

**Comment by Vb2341** [comment]
Well, it seems to work, closing!
