### ISSUE TITLE
Enhancement to move_files.py

### ISSUE THREAD

**Issue by matt-mcmaster** [Vb2341/ReDCaT#24]
Instead of having move_files generate a directory in the /ifs/redcat area based on the date of delivery, the /ifs/redcat directory should have the same name as the one in /grp/redcat/staging.  If an instrument team sends in more than one delivery on a given day, or the ReDCaT Team makes more than one delivery for a given instrument in a day, move_files can't make the directory on /ifs/redcat for the second (and any subsequent) delivery because it was already created during the first delivery.  Having move_fles name the /ifs/redcat directory the same as the one on /grp/redcat/staging would eliminate this, as well as make it easier tracking things in case of problems.

**Comment by Vb2341** [comment]
This should be fixed with 26e6d79, Instead of parsing each the year, month and day separately, it now just uses everything past the substring containing the instrument name.

That said, if a delivery directory in the staging area is named WFC3_2017_06_27_no_one_expects_the_spanish_inquisition that's exactly what will appear in the /ifs/redcat tree.  So let's hope everyone's naming conventions are well behaved.
