### ISSUE TITLE
Renaming Configuration Files in jwst_etc_check

### ISSUE THREAD

**Issue by matt-mcmaster** [Vb2341/ReDCaT#42]
Would it be possible to rename the configuration files that are being delivered?  Currently, they're coming in as <insturment>.json, but should look like: jwst_<insturment>_cofiguration.json.

After checking and adding the timestamp, the json files should look like:
jwst_<instrument>_configuration_<timestamp>.json

If not, I'll see if I can get the JWST ETC folks to do it.

**Comment by Vb2341** [comment]
Okay so, I want to make sure I have the right idea:

The files come in (from the instrument teams) as something like jwst_nircam.json, however, we want them to look like:

`jwst_nircam_<timestamp>_configuration.json`
or is it:
`jwst_nircam_configuration_<timestamp>.json`

I see the files in the most recent pandeia directory are in the latter format.  This should be an easy fix, I just need to make sure I actually fix it instead of "fixing" it by doing the wrong thing.

**Comment by matt-mcmaster** [comment]
The name of the file (before the timestamp is added) should be:
jwst_nircam_configuration.json

The templates the instrument teams are using contain only the instrument name.  I could ask the JWST ETC folks to update the names of the templates, but they tend to take a long time in responding.  If this is a straightforward fix, we could probably get it done much faster than they could.

Matt

**Comment by Vb2341** [comment]
Oh I see, so the script should add both the timestamp and configuration file suffix?  That should be easy enough.

**Comment by matt-mcmaster** [comment]
Configuration and timestamp suffix, and the jwst prefix.

Matt

**Comment by matt-mcmaster** [comment]
It may be best to check the name of the json file and add whatever is missing.

Matt

From: Matt McMaster <mcmaster@stsci.edu>
Date: Monday, September 11, 2017 at 11:57 AM
To: Vb2341/ReDCaT <reply@reply.github.com>, Vb2341/ReDCaT <ReDCaT@noreply.github.com>
Cc: Author <author@noreply.github.com>, Matt McMaster <mcmaster@stsci.edu>
Subject: Re: [Vb2341/ReDCaT] Renaming Configuration Files in jwst_etc_check (#42)

Configuration and timestamp suffix, and the jwst prefix.

Matt

**Comment by Vb2341** [comment]
The naming of the configuration files has been explicitly forced with updates in baf1c4e.  Closing.
